image: ubuntu:16.04

stages:
  - build
  - tests

default:
  before_script:
    - apt-get update -y
    - apt install curl zip unzip wget -y
    - wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install ./google-chrome-stable_current_amd64.deb -y
    - curl -s "https://get.sdkman.io" | bash
    - source "$HOME/.sdkman/bin/sdkman-init.sh"
    - sdk version
    - sdk ls java
    - sdk install java 11.0.10

build:
  stage: build
  script:
    - ./gradlew clean assemble

ui-tests:
  stage: tests
  script:
    - ./gradlew clean test allureReport