dist: trusty

language: java

addons:
  chrome: stable

before_install:
  - curl -s https://aerokube.com/cm/bash | bash && ./cm selenoid start --vnc --tmpfs 128

cache:
  directories:
    - $HOME/.gradle

jdk:
  - openjdk11

script:
  - chmod +x ./.upload_reports.sh
  - ./gradlew clean test allureReport

after_script:
  - ./.upload_reports.sh